### ISSUE TITLE
Make it part of SVGR

### ISSUE THREAD

**Issue by gregberge** [restlessbit/parcel-plugin-react-svg#1]
Hello,

I think about making an official Parcel plugin for SVGR, would you like to work on it?

Thanks!

**Comment by realplatanopapi** [comment]
Yeah that'd be great! Were you thinking of adding it as a new package under here: https://github.com/smooth-code/svgr/tree/master/packages?

**Comment by gregberge** [comment]
@restlessbit yeah exactly, you can submit a PR with the initial work, I will complete it if necessary!

**Comment by realplatanopapi** [comment]
Opened a PR 🕺
